create database if not exists global_education; 

use global_education;

ALTER TABLE GL_EDUCATION
CHANGE COLUMN `Countries_and_areas` Country varchar(255);

ALTER TABLE UNIVER_COUNTRIES
CHANGE COLUMN `COUNT OF TOP UNIVERSITIES` COUNT_OF_TOP_UNI varchar(255);

ALTER TABLE GL_EDUCATION
CHANGE COLUMN `Pre-Primary_Age_Female` Pre_Primary_Age_Female varchar(255);

ALTER TABLE GL_EDUCATION
CHANGE COLUMN `Upper-Secondary_Age_Male` Upper_Secondary_Age_Male varchar(255);

ALTER TABLE UNIVER_COUNTRIES
MODIFY COLUMN COUNT_OF_TOP_UNI INTEGER;

SELECT COUNTRY, GRADE_2_3_PROFICIENCY_MATH AS MATH_PROFICIENCY
FROM GL_EDUCATION
ORDER BY COUNTRY;

SELECT COUNTRY, GRADE_2_3_PROFICIENCY_READING AS READING_PROFICIENCY
FROM GL_EDUCATION
ORDER BY COUNTRY;

SELECT COUNTRY, PRE_PRIMARY_AGE_FEMALE AS OOSR_PRE_PRIMARY_AGE_FEMALE, PRE_PRIMARY_AGE_MALE AS OOSR_PRE_PRIMARY_AGE_MALE
FROM GL_EDUCATION 
WHERE PRE_PRIMARY_AGE_FEMALE > 10
AND PRE_PRIMARY_AGE_MALE > 10
ORDER BY COUNTRY;

SELECT COUNTRY, PRIMARY_AGE_FEMALE AS OOSR_PRIMARY_AGE_FEMALE, PRIMARY_AGE_MALE AS OOSR_PRIMARY_AGE_MALE
FROM GL_EDUCATION 
WHERE PRIMARY_AGE_FEMALE > 10
AND PRIMARY_AGE_MALE > 10
ORDER BY COUNTRY;

SELECT COUNTRY, LOWER_SECONDARY_AGE_FEMALE AS OOSR_LOWER_SECONDARY_AGE_FEMALE, LOWER_SECONDARY_AGE_MALE AS OOSR_LOWER_SECONDARY_AGE_MALE
FROM GL_EDUCATION 
WHERE LOWER_SECONDARY_AGE_FEMALE > 20
AND LOWER_SECONDARY_AGE_MALE > 20
ORDER BY COUNTRY;

SELECT COUNTRY, UPPER_SECONDARY_AGE_FEMALE AS OOSR_UPPER_SECONDARY_AGE_FEMALE, UPPER_SECONDARY_AGE_MALE AS OOSR_UPPER_SECONDARY_AGE_MALE
FROM GL_EDUCATION 
WHERE UPPER_SECONDARY_AGE_FEMALE > 42
AND UPPER_SECONDARY_AGE_MALE > 42
ORDER BY COUNTRY;

SELECT COUNTRY, UNEMPLOYMENT_RATE, GRADE_2_3_PROFICIENCY_MATH AS MATH_PROFICIENCY
FROM GL_EDUCATION
WHERE GRADE_2_3_PROFICIENCY_MATH > 0
AND UNEMPLOYMENT_RATE < 16
ORDER BY COUNTRY;

SELECT COUNTRY, UNEMPLOYMENT_RATE, GRADE_2_3_PROFICIENCY_READING AS READING_PROFICIENCY
FROM GL_EDUCATION
WHERE GRADE_2_3_PROFICIENCY_READING > 0
AND UNEMPLOYMENT_RATE < 16
ORDER BY COUNTRY;

SELECT COUNTRY, UNEMPLOYMENT_RATE, GRADE_2_3_PROFICIENCY_MATH AS MATH_PROFICIENCY
FROM GL_EDUCATION
WHERE GRADE_2_3_PROFICIENCY_MATH > 0
ORDER BY COUNTRY;

SELECT COUNTRY, UNEMPLOYMENT_RATE, GRADE_2_3_PROFICIENCY_READING AS READING_PROFICIENCY
FROM GL_EDUCATION
WHERE GRADE_2_3_PROFICIENCY_READING > 0
ORDER BY COUNTRY;

SELECT COUNTRY, COUNT_OF_TOP_UNI, UNEMPLOYMENT_RATE 
FROM UNIVER_COUNTRIES
JOIN GL_EDUCATION
ON UNIVER_COUNTRIES.COUNTRY = GL_EDUCATION.COUNTRIES_AND_AREAS
ORDER BY 'COUNT OF TOP UNIVERSITIES', 'UNEMPLOYMENT RATE';

SELECT COUNTRY, COUNT_OF_TOP_UNI, BIRTH_RATE
FROM UNIVER_COUNTRIES
JOIN GL_EDUCATION
ON UNIVER_COUNTRIES.COUNTRY = GL_EDUCATION.COUNTRIES_AND_AREAS
ORDER BY 'COUNT OF TOP UNIVERSITIES', 'BIRTH RATE';

SELECT COUNTRY, COUNT_OF_TOP_UNI, (COMPLETION_RATE_UPPER_SECONDARY_FEMALE + COMPLETION_RATE_UPPER_SECONDARY_MALE) AS UPPER_SECONDARY_COMPLETION_RATE
FROM UNIVER_COUNTRIES
JOIN GL_EDUCATION
ON UNIVER_COUNTRIES.COUNTRY = GL_EDUCATION.COUNTRIES_AND_AREAS
WHERE (COMPLETION_RATE_UPPER_SECONDARY_FEMALE + COMPLETION_RATE_UPPER_SECONDARY_MALE) > 0
ORDER BY 'COUNT OF TOP UNIVERSITIES' DESC;

SELECT COUNTRY, COUNT_OF_TOP_UNI, (GRADE_2_3_PROFICIENCY_READING + GRADE_2_3_PROFICIENCY_MATH) AS MATH_AND_READING_SKILLS
FROM UNIVER_COUNTRIES
JOIN GL_EDUCATION
ON UNIVER_COUNTRIES.COUNTRY = GL_EDUCATION.COUNTRIES_AND_AREAS
WHERE GRADE_2_3_PROFICIENCY_READING > 0
OR GRADE_2_3_PROFICIENCY_MATH > 0
ORDER BY COUNT_OF_TOP_UNI DESC;


